### PR TITLE
Refactor front end with ts files only

### PR DESCRIPTION
**Pull request by henrikra**
Now frontend has only TS files that you as developer need to modify! 🎉 
Say good bye to `MMM-awesome-alexa.js` and say hello to `MMM-awesome-alexa.TS`.

The ultimate goal here is that we should only ever need to modify TS files and only compile them to JS files.

New flow when developing frontend:
1. Modify `MMM-awesome-alexa.ts` or other TS files under `src/renderer` folder
2. Run `npm run webpack` to compile to one `MMM-awesome-alexa.js`
3. Test 
4. profit!

I am next trying to add seconds webpack config for bundling the backend part. But I have ran into problems with that since I am getting errors with aws-sdk not being found. But I will post it as separate PR when I have solved that. But this pr helps when developing the front end :)

EDIT: I managed to get server side also only to TS files!!! I will make new PR when this is in :)

### CODE REVIEW

**Comment by henrikra** [comment]
@dolanmiu Can you verify this is working for you? :)

**Comment by dolanmiu** [comment]
Just tested

Wow, it works very nicely

Deleted `dist` and the `MMM-awesome-alexa.js` files and re-built just for sanity checking, and that works too

Great work!

What happened to the AlexaMirror class though?

Will merge when passing CI

**Comment by henrikra** [comment]
> What happened to the AlexaMirror class though?

I merged its content to `src/renderer/MMM-awesome-alexa.ts` ;)

The CI is complaining about linting stuff. I have fixed those linting errors already in my upcoming pr. So if we can merge this and you get lint fixes in next pr, is that okay to you? 🎉

**Comment by dolanmiu** [comment]
Sure thing 😄

**Comment by dolanmiu** [comment]
@henrikra What is your reason behind using `100`? I generally don't put a limit because we all have 24 inch screens and above

**Pull request merged**
