### PR TITLE
chore(package): update webpack to version 4.1.1

### PR DESCRIPTION
**Pull request by dolanmiu**
Closes #77 
Trying to update webpack to v4

Need to use webpack-cli too

### CODE REVIEW

**Comment by dolanmiu** [comment]
@henrikra take a look at this

Updates to the latest webpack v4!

**Comment by dolanmiu** [comment]
I cant test this until Friday when I go on my mac 😭 

Can you test it if it works for you? Then we merge?

**Comment by henrikra** [comment]
Of course I have tested this 🤣 As you can see I have updated the bundles and also I have run them. But yeah test on Friday and if it works for you then merge it :)

**Comment by justjim1220** [comment]
Can I test it on my Windows MMirror?

**Comment by dolanmiu** [comment]
@justjim1220 sure go ahead!

I don't have a mic on my windows, and don't have headset, so I never bothered setting it up

**Comment by dolanmiu** [comment]
Works on my mac, updated to `4.4.1` and that also works

Updated to 4.4.1, and will merge :D

**Pull request merged**
