### PR TITLE
Add node script for token

### LINKED ISSUE #14: Invalid Grant Parameter
When I run the code:

```
CLIENT_ID="amzn1.application-oa2-client.2ce85ab0db2d4e9..."
CLIENT_SECRET="4247e7121f974bd0dc964d99e3dfa445b8572e..."
CODE="ANudVcrBPTyYrgKMHhtu"
GRANT_TYPE="authorization_code"
REDIRECT_URI="https://localhost:9745/authresponse"

curl -X POST --data "grant_type=${GRANT_TYPE}&code=${CODE}&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&redirect_uri=${REDIRECT_URI}" https://api.amazon.com/auth/o2/token
```

i get the following error:
`{"error_description":"The request has an invalid grant parameter : code","error":"invalid_grant"}`
can anyone help me?

### LINKED ISSUE #57: Unable to get AVS Token
Hi there, I've setup an account and created an 'app' for the AVS on the Amazon developer's site but I'm not able to complete the setup by getting the access token to generate the config.

I'm able to get to the Amazon login page and see the prompt about 'when you click okay, we'll provide Magic Mirror connectivity to Amazon Alexa" ('Magic Mirror' is the name of my AVS 'app').

Unfortunately, when I hit okay, I'm directed to an Amazon Error page stating "we're sorry! an error has occurred when we tried to process your request, etc".

I've tried the method using the auth_code.sh and auth_code2.sh bash scripts but ultimately received the same 'we're sorry' error message from Amazon.

Any idea where I could have gone wrong?

### LINKED ISSUE #81: Make NodeJS script to replace shell scripts
Looks like lots of people have trouble running shell scripts so maybe we should make better script with node so it would be easier to use? Or do you have any other ideas @dolanmiu ?

### PR DESCRIPTION
**Pull request by henrikra**
I have added a node script so it will be easy to get tokens etc for this module. Please checkout the new installation guide and tell me if you got it working now @seattlecajun @dolanmiu @vivekpk007 @nitrogen73 @devmil @DaDonkDon @Albiorix2016 @atimon @NilSkilz @cowboysdude @adbang @sobrien556

Enjoy 🔥 
Fixes #81 
Fixes #14 
Fixes #57

### CODE REVIEW

**Comment by dolanmiu** [comment]
I am gonna try this :)

**Comment by dolanmiu** [comment]
Browser does not open, I am on my Windows 10 machine!

**Comment by Albiorix2016** [comment]
im sorry im still fairly new to this, do i just download the new files on my windows pc and ftp them to the pi? i did a git pull but it did not update or add the new files you created

**Comment by Albiorix2016** [comment]
ok so i just merged the files and ran the first code and this is what it returns for me


` node src/aws-token-helper/aws-token-helper.js/home/pi/MagicMirror/modules/MMM-awesome-alexa/src/aws-token-helper/aws-token-helper.js:7
<!DOCTYPE html>
^

SyntaxError: Unexpected token <
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
`

**Comment by dolanmiu** [comment]
@Albiorix2016 you need to npm install first

**Comment by Albiorix2016** [comment]
@dolanmiu thank you i just ran the install and i get this at the end. is that a problem?

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
`

**Comment by dolanmiu** [comment]
@Albiorix2016 yup that looks normal, its not an `ERROR`, its a `WARN`, which isnt bad

**Comment by Albiorix2016** [comment]
Ok that seemed to have fixed that issue. Now i go through and enter the info the script asks for but it does not open a browser window

**Comment by cowboysdude** [comment]
Awesome!

**Comment by henrikra** [comment]
@Albiorix2016 Try to run those scripts on your own computer and not on Raspberry PI :D

**Comment by henrikra** [comment]
> Can we use async await on this? The nesting looks ugly

Hmm I am not sure if it is good idea because MagicMirror installs node v6 by default which does not have that feature yet Can we use async await on this? The nesting looks ugly

> Also, i was thinking of adding it as an npm command:

This is a good idea!

**Comment by henrikra** [comment]
@Albiorix2016 Did you run the script on OSX, Windows or what?

**Comment by henrikra** [comment]
I have now update the branch with different `opn` library which should open browser. Make sure to pull the latest changes and run `npm i` before testing.

**Comment by henrikra** [comment]
Lol there is `avs-options.ts` file too ;) Hmm are you sure? For example in `audio-service.ts` in `url` there is `avs` 🤔

**Comment by dolanmiu** [comment]
Yeah, AWS should be AVS

**Comment by henrikra** [comment]
@dolanmiu Fixed. Did you get your browser open now with `opn` library?

**Comment by sobrien556** [comment]
What directory do you run the "npm run avs-token-helper" command from?

**Comment by sobrien556** [comment]
Getting this everytime I run the command from the MMM-awesome-alexe root folder:

npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "avs-token-helper"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10

npm ERR! missing script: avs-token-helper
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/modules/MMM-awesome-alexa/npm-debug.log

**Comment by henrikra** [comment]
@sobrien556 Have you used git before? You have to change branch first to `add-node-script-for-token`. Then you have to use git to pull latest files. Please watch this: https://www.youtube.com/watch?v=HVsySz-h9r4 and ask if you still dont have the new files :)

**Comment by henrikra** [comment]
@dolanmiu Can you debug windows more because I dont have it? xD Try to modify `generateQuery`. For example change:
`.map((key: string) => key + "=" + params[key])`
to
`.map((key: string) => key + "=" + encodeURIComponent(params[key]))`

**Comment by henrikra** [comment]
@dolanmiu Can you send me private message on gitter and tell me your parameters you gave to the script so I can test if they work on my machine?

**Comment by dolanmiu** [comment]
@henrikra will do after work

Btw, how are you building those .js files? Can I build them too? It doesn't seem to be an npm command for that

**Comment by henrikra** [comment]
Great. I just used tsc command to compile them

**Comment by Albiorix2016** [comment]
here is the error im getting when i run the npm, i thought i was using the right versions that worked with MM already, is that my problem?

`> mmm-awesome-alexa@1.0.0 avs-token-helper /home/pi/MagicMirror/modules/MMM-awesome-alexa
> node src/avs-token-helper/avs-token-helper.js

/home/pi/MagicMirror/modules/MMM-awesome-alexa/src/avs-token-helper/avs-token-helper.js:25
                    )
                    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "avs-token-helper"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mmm-awesome-alexa@1.0.0 avs-token-helper: `node src/avs-token-helper/avs-token-helper.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 avs-token-helper script 'node src/avs-token-helper/avs-token-helper.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mmm-awesome-alexa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/avs-token-helper/avs-token-helper.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mmm-awesome-alexa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mmm-awesome-alexa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/modules/MMM-awesome-alexa/src/npm-debug.log
`

**Comment by henrikra** [comment]
@Albiorix2016 type `git log` and tell me latest commit message. It should work now

**Comment by Albiorix2016** [comment]
@henrikra 
`commit a90b5ca2c1ab7c4bc69db72856d6056d76b67573
Author: Dolan <dolan_miu@hotmail.com>
Date:   Thu Mar 8 02:12:09 2018 +0000

    Fix for windows

commit 79c4286fa49521e7950703be80cfcc4fedc70e98
Author: Dolan <dolan_miu@hotmail.com>
Date:   Thu Mar 8 02:05:53 2018 +0000

    Rename files

commit e415176687d1f7bd77d51e8089c7bf47302f4f7f
Author: Henrik Raitasola <henrik.raitasola@gmail.com>
Date:   Wed Mar 7 22:34:32 2018 +0200

    Correct typo

commit dcac67fc5cd6fb9db238db1b567dada7a1fb23d2
Author: Henrik Raitasola <henrik.raitasola@gmail.com>
Date:   Wed Mar 7 09:31:44 2018 +0200

    Add npm scripts
`

**Comment by dolanmiu** [comment]
@henrikra btw, ive messaged you on gitter

**VERY VERY** interesting

This script works flawlessly on my mac, and I even got the correct response!!

Windows gets the Amazon error that I print screened above.

```
http://localhost:4200/authresponse?code=ANj............&scope=alexa%3Aall
```

**Comment by henrikra** [comment]
@dolanmiu Messaged you back

**Comment by dolanmiu** [comment]
@henrikra Another interesting discovery:

I console logged the url and **pasted** it into Chrome, and it **WORKS PERFECTLY**

The URL for on Windows when it opens automatically is:

```
https://www.amazon.com/ap/oa?client_id=amzn1.application-oa2-client.9cfa748077654ec183867d32a^&scope=alexa:all^&scope_data={\alexa:all\:{\productID\:\avs_v2_test\,\productInstanceAttributes\:{\deviceSerialNumber\:123}}}^&response_type=code^&redirect_uri=http://localhost:4200/authresponse
```

Which is much different from:

```
https://www.amazon.com/ap/oa?client_id=amzn1.application-oa2-client.9cfa748077654ec183867d32a&scope=alexa:all&scope_data={"alexa:all":{"productID":"avs_v2_test","productInstanceAttributes":{"deviceSerialNumber":123}}}&response_type=code&redirect_uri=http://localhost:4200/authresponse
```

(I deleted some parts for security)

**Comment by henrikra** [comment]
So second url is the url that you console logged? At least for some reason it adds these weird `^` characters

**Comment by dolanmiu** [comment]
Second one is console logged yes

**Comment by henrikra** [comment]
Hmm I can't debug this since I don't have windows. Can you still debug it more? Atleast we know that the link is ok right? So you just need to find a way to open a link on windows in a way that the link doesn't get fucked up :D

**Comment by dolanmiu** [comment]
@henrikra 
> in a way that the link doesn't get fucked up :D

Haha yes, I will try tonight

**Comment by henrikra** [comment]
Yeah. But I am pretty sure you can figure out how we don't need to do that :D

**Comment by dolanmiu** [comment]
Found something maybe useful:

https://github.com/sindresorhus/opn/issues/44

**Comment by henrikra** [comment]
Nice! Can you try to use that replacement in the script?

**Comment by dolanmiu** [comment]
I actually found the line which does this:

https://github.com/sindresorhus/opn/blob/b9f7e569f5a3d5d520047df3e9f10a42d52fd9d4/index.js#L36

https://github.com/sindresorhus/opn/issues/77

**Comment by dolanmiu** [comment]
Im not sure if we can, because the `^&` is way after we call `opn`

It has something to do with adding spaces:

https://github.com/sindresorhus/opn/pull/47

**Comment by henrikra** [comment]
But we are not adding spaces?

**Comment by dolanmiu** [comment]
Maybe the problem isn't `^&`, but it is to do with the JSON escaping

I will investigate tonight

**Comment by henrikra** [comment]
Thanks 👍

**Comment by dolanmiu** [comment]
Two issues:

`^&` and the json is also escaped, which breaks it

I even tried `openner`: https://www.npmjs.com/package/opener

And that still didn't work

Don't think its possible with windows, so I made it `console.log` the url out if its windows!

Moved the js files into a `/avs-helper` directory as I don't like the compiled files to be in `/src`

Made a build command to build the avs-helper files

**Comment by henrikra** [comment]
True. Nice! I have to do some final testing. @Albiorix2016 Can you pull latest changes and try it now. You used windows right?

**Comment by dolanmiu** [comment]
@henrikra @Albiorix2016 Oh I forgot, I need to amend `avs-refreshToken-helper` too :joy: 

I only did `avs-token-helper`

**Comment by Albiorix2016** [comment]
@henrikra 

seems to be getting further along now

npm run avs-token-helper

> mmm-awesome-alexa@1.0.0 avs-token-helper /home/pi/MagicMirror/modules/MMM-awesome-alexa
> node avs-helper/avs-token-helper.js

Welcome to the Amazon auth helper!
I will need three things from you:
- Client ID
- Product ID
- Allowed return URL
[Press any key to continue]
Client ID? amzn1.application-oa2-client...
Product Id? ...
Redirect URI (allowed return URL)? https://localhost:9745/authresponse
Great! Next I will now open a browser where you can authorize your Alexa product
[Press any key to continue]
(node:7896) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
``

idk if its my return url or what but i never get past this part regardless of method lol

**Comment by dolanmiu** [comment]
@Albiorix2016 Can you try again? I have added logging of the error, and then paste the error you are having.

It is failing on `opn`, so I am guessing it's something to do with your browser, but lets see

**Comment by Albiorix2016** [comment]
@dolanmiu 

`Redirect URI (allowed return URL)? https://localhost:9745/authresponse
Great! Next I will now open a browser where you can authorize your Alexa product
[Press any key to continue]
Something went wrong with opening your browser
Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/opn/index.js:84:13)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
`

i use google chrome on win10 if that helps using putty

**Comment by henrikra** [comment]
@Albiorix2016 You should run these scripts on your host machine. Not on raspberry pi. Can you tell me what is your setup?

**Comment by Albiorix2016** [comment]
@henrikra i've been using a win10 machine with an 15 cpu and using putty to ssh into the pi3

**Comment by E3V3A** [comment]
@henrikra 

> > Can we use async await on this? The nesting looks ugly
>
>Hmm I am not sure if it is good idea because MagicMirror installs node v6 by default which does not 
> have that feature yet https://github.com/MichMich/MagicMirror/blob/master/installers/raspberry.sh#L85

A PR upping this to 9.x was just merged to `dev` a few days ago.

**Comment by henrikra** [comment]
@Albiorix2016 can you use the scripts if you run them on your windows machine?

**Comment by dolanmiu** [comment]
@henrikra I have noticed a potential problem, if @Albiorix2016 uses it on windows, he needs to also set up `SoX` and `npm install` etc, which is quite difficult on windows actually

**Comment by henrikra** [comment]
True. Automatic browser opening is just a plus. Maybe even remove `opn` library and always just console.log it?

**Comment by dolanmiu** [comment]
@henrikra 

> Maybe even remove opn library and always just console.log 

yes good idea, `opn` add more complexity which makes our lives more difficult :joy:

**Comment by henrikra** [comment]
Yeah. Everybody has browser open all the time anyways :D

**Comment by E3V3A** [comment]
I'm trying to test the scripts, but I'm stuck after copying them from repo to my local master clone. Not feeling like doing the entire compile install again, what are the missing installs needed for the scripts to work?

Now I get: 
```bash
# npm run avs-token-helper

npm ERR! missing script: avs-token-helper
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-03-15T19_57_47_376Z-debug.log

# OR after adding a shebang
# ./avs-token-helper.js

module.js:545
    throw err;
    ^

Error: Cannot find module 'opn'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/avs-helper/avs-token-helper.js:6:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by henrikra** [comment]
Hehe. Actually I just update the branch. Please pull the latest changes :)

**Comment by Albiorix2016** [comment]
so do i need to pull again and try the scripts from putty or do i need to install sox and what not on my win box?

**Comment by henrikra** [comment]
@Albiorix2016 pull latest yes. Then run those scripts on windows 👍

**Comment by Albiorix2016** [comment]
@henrikra  ok those seemed to work. is the refresh token extremely long?

**Comment by Albiorix2016** [comment]
i guess i did something wrong, i loaded the module in to my config and turned on visualization, i use alexa as the wake word and the white circle shows up when i say alexa but then after a command the circle fills to a white dot but never get a audio response

**Comment by henrikra** [comment]
@Albiorix2016 Token scripts are working then! @dolanmiu can you do final testing and lets merge this?

**Comment by Albiorix2016** [comment]
Any idea why I’m not getting any response from commands other than the
circle/dot?

**Comment by E3V3A** [comment]
Ok, I just tried this using:

* Redirect URI (allowed return URL)?  `https://localhost:9745/authresponse`

```bash
$ npm run avs-token-helper

> mmm-awesome-alexa@1.0.0 avs-token-helper /home/pi/MagicMirror/modules/MMM-awesome-alexa
> node avs-helper/avs-token-helper.js

Welcome to the Amazon auth helper!
I will need three things from you:
- Client ID
- Product ID
- Allowed return URL
[Press any key to continue]

Client ID? amzn1.application-oa2-client.xxxx
Product Id? A1xxxxx
Redirect URI (allowed return URL)? https://localhost:9745/authresponse
Great! Copy paste the link below to your browser to authorize your Alexa product

https://www.amazon.com/ap/oa?client_id=amzn1.application-oa2-client.xxxx&scope=alexa:all&scope_data={"alexa:all":{"productID":"A1xxxx","productInstanceAttributes":{"deviceSerialNumber":123}}}&response_type=code&redirect_uri=https://localhost:9745/authresponse
```

Pasted this into chrome, got feedback that I login from unusual place, got feedback code, confirmed, went on to accept api usage... back to same "We're sorry message". No go! 

* For those of you, which this works, what country are you connecting from?
* Are you using same URL

Questions: 
* What you call ` Product ID`, is that the same as Amazon developer console calls `Amazon ID`??

**Comment by Albiorix2016** [comment]
@E3V3A i finally got mine to work, its setup as a device and the product id should be able to find if you go to the "my projects dashboard"

**Comment by henrikra** [comment]
@E3V3A when you get "We're sorry message" then there is usually a link that will open more details of your problem

**Comment by dolanmiu** [comment]
Can this be merged now?

**Comment by henrikra** [comment]
Yes! Let's try it out and let's fix if problems occur :)

**Comment by onkararj** [comment]
im getting this error


This site can’t be reached

localhost refused to connect.

**Comment by dolanmiu** [comment]
That is expected

All the info is in the address bar

**Pull request merged**
