### PR TITLE
Remove PM2 info

### PR DESCRIPTION
**Pull request by henrikra**
I have always used PM2 on Raspberry with this module and haven't had any problems

### CODE REVIEW

**Comment by dolanmiu** [comment]
PM2 fails on me though :sob: 

Maybe move this to the Wiki?

**Comment by henrikra** [comment]
On Raspberry?

**Comment by dolanmiu** [comment]
Yeah Raspberry Pi 3, PIXEL

MagicMirror with `MMM-awesome-alexa` starts up, but it doesn't recognize my voice

**Comment by henrikra** [comment]
Are you sure your sounds settings are correct?

**Comment by dolanmiu** [comment]
Yeah, it only works if I do:

```bash
$ export AUDIODEV=hw:1,0
```

from: https://www.raspberrypi.org/forums/viewtopic.php?t=13088&p=332703

**Comment by henrikra** [comment]
Did you try this: 
Because I have almost same asoundrc file :)

image

**Comment by dolanmiu** [comment]
Havent tried that 

Where did u get that snippet from?

**Comment by henrikra** [comment]
From you Raspberry link :D

**Comment by dolanmiu** [comment]
I have this mic:

https://www.amazon.co.uk/Mini-Microphone-Compatible-Raspberry-mi-305/dp/B072W1SS6B/ref=sr_1_3?ie=UTF8&qid=1519352144&sr=8-3&keywords=usb+mic+raspberry+pi

It's quite cheap and nice xD

No set up, its plug and play. 

All I need to do is run that stupid command `export AUDIODEV=hw:1,0` everytime 😭

**Comment by henrikra** [comment]
That means that you haven't set right audio card or device as default for your mic. Please check my post https://github.com/dolanmiu/MMM-awesome-alexa/issues/74#issuecomment-362855026

I can't the command by heart which tell you on which device you have your mic etc. But I guess you can find those. Can you print them here?

**Comment by dolanmiu** [comment]
Thank you so much, your suggestion worked!!

Now I can use PM2 + MM + alexa

**Comment by dolanmiu** [comment]
Since I need to type:

```bash
$ export AUDIODEV=hw:1,0
```

And

the config now has:

```json
capture.pcm {
     type plug
     slave.pcm "hw:1,0"
}
```

It now has `hw:1,0`

So I assume thats why 😂

**Comment by henrikra** [comment]
basically it sets right card to be your default sound card.

**Pull request merged**
