### PR TITLE
Feat/prettier clean up

### PR DESCRIPTION
**Pull request by dolanmiu**
Make the package.json more friendly to read

prettier takes advantage of `.prettierrc.yml`, it doesn't know anything about `.vscode`

So it is moved to the former file

### CODE REVIEW

**Comment by henrikra** [comment]
Hmm I dont get it what this change does? I mean VSCode plugin read those settings for Prettier plugin in .vscode folder 🤔

**Comment by dolanmiu** [comment]
Yeah, but notice how the package.json command is more verbose before

Now the package.json command is way cleaner

**Comment by henrikra** [comment]
Hmm I tried your branch and for some reason prettier is not working for me 🤔 What about you?

**Comment by dolanmiu** [comment]
Works for me just fine, seems to work in Travis CI too:

https://travis-ci.org/dolanmiu/MMM-awesome-alexa/builds/342791278?utm_source=github_status&utm_medium=notification

**Comment by henrikra** [comment]
I mean when I am using VSCode it doesn't format my code anymore. What about when you try with VSCode?

**Comment by dolanmiu** [comment]
oh i see, ill check VSCode later

It's because I removed settings .vscode

**Comment by dolanmiu** [comment]
Works for me, `shift + alt + f` works and formats for me

**Comment by dolanmiu** [comment]
When I last checked

 "prettier -l src/**/*.ts" 

Doesn’t work on windows xD 

I’ll check again tonight

**Comment by henrikra** [comment]
So on Windows it didn't work without quotes?

**Comment by dolanmiu** [comment]
Yeah it doesnt work without quotes on windows, it gets confused with the /**/*

**Comment by dolanmiu** [comment]
@henrikra you were right actually, removing the quotes like: `prettier -l src/**/*.ts` works! Will make a PR soon simplifying it

**Comment by henrikra** [comment]
Good to hear!

**Pull request merged**
